# Generated by Django 3.2.13 on 2022-11-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postgraduate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('degree', models.SmallIntegerField(choices=[(1, '硕士生毕业'), (2, '博士生毕业')], verbose_name='学历')),
                ('specialty', models.SmallIntegerField(choices=[(1, '计算机技术与资源信息工程'), (2, '计算机技术'), (3, '软件工程'), (4, '计算机科学与技术')], verbose_name='专业')),
                ('grade', models.CharField(max_length=4, verbose_name='年级')),
                ('year', models.CharField(max_length=4, verbose_name='毕业年度')),
                ('pgraduation', models.SmallIntegerField(choices=[(1, '劳动合同'), (2, '协议就业'), (3, '未就业'), (4, '非派遣'), (5, '考取升学'), (6, '自主创业'), (7, '出国（境）学习'), (8, '定向就业')], verbose_name='预计就业类型')),
                ('rgraduation', models.SmallIntegerField(choices=[(1, '劳动合同'), (2, '协议就业'), (3, '未就业'), (4, '非派遣'), (5, '升学'), (6, '自主创业'), (7, '出国'), (8, '定向'), (9, '部队文职')], verbose_name='实际就业类型')),
                ('organization', models.CharField(blank=True, max_length=100, null=True, verbose_name='就业升学单位')),
                ('location', models.CharField(max_length=50, verbose_name='单位所在地')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='目前状况')),
            ],
        ),
        migrations.CreateModel(
            name='Undergraduate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='年度')),
                ('student_id', models.CharField(max_length=10, verbose_name='学号')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('graduation', models.SmallIntegerField(choices=[(1, '升学'), (2, '非派遣/劳动合同'), (3, '签约就业'), (4, '出国学习'), (5, '定向就业'), (6, '灵活就业')], verbose_name='毕业去向')),
                ('organization', models.CharField(blank=True, max_length=100, null=True, verbose_name='实际单位')),
                ('location', models.CharField(max_length=50, verbose_name='单位所在地')),
                ('affiliation', models.CharField(blank=True, max_length=50, null=True, verbose_name='单位隶属')),
                ('nature', models.SmallIntegerField(choices=[(1, '三资企业'), (2, '国有企业'), (3, '升学'), (4, '出国、出境'), (5, '灵活就业'), (6, '科研设计单位'), (7, '艰苦行业企业'), (8, '其他企业'), (9, '未就业')], verbose_name='单位性质')),
                ('type', models.SmallIntegerField(choices=[(1, '211院校'), (2, '985院校'), (3, '世界500强'), (4, '其他')], verbose_name='单位类型')),
                ('industry', models.SmallIntegerField(choices=[(1, '制造业'), (2, '信息传输软件和信息技术服务业'), (3, '采矿业'), (4, '交通运输、仓储和邮政业'), (5, '租赁和商业服务业'), (6, '金融业'), (7, '建筑业'), (8, '科学研究和技术服务业'), (9, '科学研究和技术服务业'), (10, '军队'), (11, '教育'), (12, '其他')], verbose_name='行业性质')),
            ],
        ),
    ]
